In [1]:
import os
from lib2to3.btm_matcher import type_repr


In [2]:
os.path.split("user/username/file.txt")

('user/username', 'file.txt')

In [3]:
from copy import deepcopy, copy

In [4]:
def printf(arg):
	print()
	print(arg)
	print([id(x) for x in arg])
	print()

In [5]:
a = [1,2]
b = [a,3]
a.append(b)
c = deepcopy(a)
d = copy(a)
printf(a)
printf(b)
printf(c)
printf(d)


[1, 2, [[...], 3]]
[140725380581816, 140725380581848, 2637633137472]


[[1, 2, [...]], 3]
[2637634658304, 140725380581880]


[1, 2, [[...], 3]]
[140725380581816, 140725380581848, 2637633136512]


[1, 2, [[1, 2, [...]], 3]]
[140725380581816, 140725380581848, 2637633137472]



In [6]:
ls1 = [1,2]
ls2 = ls1
ls1 =ls1 + [3,4]
ls2

[1, 2]

In [7]:
import numpy as np
a = np.random.randn(3,4)
a

array([[ 1.12635720e-01,  3.20214070e-02,  1.01424387e-03,
        -1.35283472e+00],
       [-1.25206909e+00,  1.71595720e-02,  6.45622423e-01,
         5.26456596e-02],
       [ 1.43107721e+00,  8.01530515e-02,  2.20597197e+00,
         1.65869692e-01]])

In [8]:
a.resize((4,3))
b = a.reshape((1,12))
b

array([[ 1.12635720e-01,  3.20214070e-02,  1.01424387e-03,
        -1.35283472e+00, -1.25206909e+00,  1.71595720e-02,
         6.45622423e-01,  5.26456596e-02,  1.43107721e+00,
         8.01530515e-02,  2.20597197e+00,  1.65869692e-01]])

In [9]:
b[0][2] = 5
a

array([[ 0.11263572,  0.03202141,  5.        ],
       [-1.35283472, -1.25206909,  0.01715957],
       [ 0.64562242,  0.05264566,  1.43107721],
       [ 0.08015305,  2.20597197,  0.16586969]])

In [10]:
print(a>0.2)

[[False False  True]
 [False False False]
 [ True False  True]
 [False  True False]]


In [11]:
print(a[a>0.2])

[5.         0.64562242 1.43107721 2.20597197]


In [12]:
a[a>0.2][2] = 3

In [13]:
a

array([[ 0.11263572,  0.03202141,  5.        ],
       [-1.35283472, -1.25206909,  0.01715957],
       [ 0.64562242,  0.05264566,  1.43107721],
       [ 0.08015305,  2.20597197,  0.16586969]])

In [14]:
c = np.transpose(a)
c[0][0] = 10
c

array([[10.        , -1.35283472,  0.64562242,  0.08015305],
       [ 0.03202141, -1.25206909,  0.05264566,  2.20597197],
       [ 5.        ,  0.01715957,  1.43107721,  0.16586969]])

In [15]:
a

array([[10.        ,  0.03202141,  5.        ],
       [-1.35283472, -1.25206909,  0.01715957],
       [ 0.64562242,  0.05264566,  1.43107721],
       [ 0.08015305,  2.20597197,  0.16586969]])

In [16]:
ls = range(4)
aa = np.random.randn(4,4)
aa

array([[-1.71326284, -1.88876437,  0.04243623,  1.67575229],
       [ 0.53508386, -1.42996803,  0.68244626,  0.18458632],
       [-2.21292296,  0.82775283,  0.34664489, -1.78868438],
       [ 1.31712174, -1.19080863, -0.12022031,  0.29856647]])

In [17]:
print(aa[ls,ls])

[-1.71326284 -1.42996803  0.34664489  0.29856647]


In [18]:
m = np.random.rand(3,7)
n = np.random.rand(7,4)
mm = m.reshape((3,7,1))
nn = n.reshape((1,7,4))
ans1 = np.sum(mm*nn, axis=1)
ans2 = m@n
print(ans1-ans2<1e-10)
print(ans1)
print(ans2)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[0.91695303 0.6596666  1.02137137 0.5459339 ]
 [1.20978362 1.05884215 0.88892929 0.59503774]
 [1.84162682 0.68911353 1.71244018 0.86272857]]
[[0.91695303 0.6596666  1.02137137 0.5459339 ]
 [1.20978362 1.05884215 0.88892929 0.59503774]
 [1.84162682 0.68911353 1.71244018 0.86272857]]


In [19]:
x = np.random.uniform(size=100)
x

array([6.51286093e-01, 6.42761817e-02, 1.21710312e-01, 5.89138005e-01,
       1.00693147e-01, 8.39040522e-01, 7.61763427e-01, 2.19953097e-01,
       9.83259839e-01, 3.67119790e-01, 2.80509032e-01, 5.81679912e-02,
       2.39260831e-03, 6.28452234e-01, 2.00799477e-01, 9.79581704e-01,
       1.10668363e-01, 4.86607460e-03, 7.64059988e-01, 9.91087620e-01,
       8.55078377e-01, 8.93584793e-01, 8.50237691e-02, 5.77090355e-01,
       9.27273975e-01, 3.26022820e-01, 8.33165629e-01, 1.36345183e-01,
       6.93130229e-02, 3.10564501e-04, 1.96991223e-01, 7.68347678e-01,
       2.53275429e-01, 3.55089868e-02, 6.17273492e-01, 4.92042523e-01,
       5.48651075e-01, 8.09541569e-01, 2.45807345e-01, 5.96333034e-02,
       3.32012495e-02, 1.89578306e-01, 8.70299192e-02, 4.45805350e-02,
       7.37289917e-01, 2.68897199e-01, 5.06709934e-01, 8.25223972e-01,
       9.11570464e-02, 1.66064565e-01, 2.31098815e-02, 6.70986645e-01,
       8.90879895e-01, 3.80081001e-01, 9.34090959e-01, 1.14167290e-01,
      

In [20]:
t = (2)
type(t)

int

In [21]:
t=(2,)
type(t)

tuple

In [22]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10,30])
x,y = np.meshgrid(x,y)

In [23]:
x

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [24]:
y

array([[ 6,  6,  6,  6,  6],
       [ 7,  7,  7,  7,  7],
       [ 8,  8,  8,  8,  8],
       [ 9,  9,  9,  9,  9],
       [10, 10, 10, 10, 10],
       [30, 30, 30, 30, 30]])

In [10]:
import torch
x = torch.tensor(-1., requires_grad=True)
x.shape

torch.Size([])

In [11]:
y = torch.zeros(1,1)
y.shape

torch.Size([1, 1])

In [12]:
z = torch.max(x, y)
z.backward()
print(x.grad)

tensor(0.)


In [28]:
y.shape

torch.Size([1, 3])

In [29]:
z = torch.tensor([[[1,2,3],[4,5,6]]])
z.shape

torch.Size([1, 2, 3])

In [30]:
%%time
a = torch.rand(100000,10000)
b = torch.rand(10000,100000)
c = a

CPU times: total: 5.19 s
Wall time: 5.24 s


In [31]:
c.device

device(type='cpu')

In [ ]:
torch.cuda.is_available()

In [34]:
a = a.cuda()
b = b.cuda()
a.device

device(type='cuda', index=0)

In [35]:
c = a@b
c

tensor([[24969.3184, 25075.1484, 25027.8848,  ..., 24996.8691, 24959.0449,
         24996.4453],
        [24971.5410, 25026.6738, 24991.3066,  ..., 25005.0547, 24962.8984,
         24995.2090],
        [24944.7988, 24989.0449, 25043.0801,  ..., 25011.0898, 25004.5820,
         24961.2695],
        ...,
        [25077.0957, 25023.2559, 25103.9531,  ..., 25049.3164, 24999.6914,
         25027.6602],
        [25012.1855, 25062.2324, 25069.1367,  ..., 25037.6738, 24992.8574,
         25071.7988],
        [24963.2207, 24982.3027, 24986.4180,  ..., 25048.4355, 24935.8301,
         24980.9121]], device='cuda:0')

In [36]:
c.device

device(type='cuda', index=0)

In [2]:
s1 = list("hello")
s2 = list("world")
s1[1:] = []
print(s1)
s1[1:] = s2
print(s1[-1])

['h']
d


In [3]:
len(str(12.23))

5

In [9]:
with open("t.txt", "r") as f:
	print(f.read(3))

hel


In [2]:
ls = [True,False,True]
s = 2
s += ls[0]
s

3

In [6]:
from copy import deepcopy
ls = [1,2,[2,3,4,ls]]
ls1 = deepcopy(ls)
print(id(ls), id(ls1))
print(id(ls[2]), id(ls1[2]))
print(id(ls[2][3]), id(ls1[2][3]))
# ls1[2][3][0] = 100
print(ls)

2169761245632 2169762573184
2169760981120 2169763166592
2169763377280 2169761244992
[1, 2, [2, 3, 4, [1, 2, [2, 3, 4, [1, 2, [2, 3, 4, [1, 2, [2, 3, 4, [1, 2, [2, 3, 4, [4, 5, 6]]]]]]]]]]]


In [15]:
class A:
	def __init__(self, x):
		self.x = x

	def deept(self):
		print("deepcopy called",self.x)
		self.print1()

	def print1(self):
		print("a")
class B(A):
	def __init__(self, x):
		super().__init__(x)
		self.x = x+"sadf"

	def print1(self):
		print("b")


t = B("hello")
p = t.deept
p()

deepcopy called hellosadf
b


In [24]:
import torch
a = torch.tensor([1, 2, 3, 4, 5])
y = a.flatten()
y

tensor([1, 2, 3, 4, 5])

In [25]:
y[0] = 100
print(a)

tensor([100,   2,   3,   4,   5])


In [3]:
class A:
	def __init__(self, name, age):
		self.name = name
		self.age = age
	def attack(self, target):
		print(f"{self.name} attacks {target.name}!")

def A_attack(self, target):
	print(f"{self.name} attacks {target.age} with a custom method!")
def B_attack(self, target):
	print(f"{self.name} attacks {target.age} with a different custom method!")

a = A("Hero", 30)
b = A("Villain", 40)
a.attack(b)  # Original method

A.attack = A_attack  # Replace method for class A
a.attack(b)  # New method for class A

b.attack = B_attack  # Replace method for instance b
b.attack(a,a)  # New method for instance b


Hero attacks Villain!
Hero attacks 40 with a custom method!
Hero attacks 30 with a different custom method!


In [6]:
def A(x,**y):
	z = []
	print(y)
	for i in y:
		z.append(i)
	z.append(x)
	return z

x = ['a','b']
y = [1,2]
print(A(x,a=y))

{'a': [1, 2]}
['a', ['a', 'b']]
