In [57]:
%%time
import torch

x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

CPU times: total: 0 ns
Wall time: 0 ns


In [58]:
%%time
# x = x.cuda()
# y = y.cuda()
# z = x.cuda()
for i in range(1,100000):
    x = x @ y

print(x)

tensor([[inf, inf],
        [inf, inf]])
CPU times: total: 156 ms
Wall time: 157 ms


In [47]:
x = torch.tensor(1.0,requires_grad=True)
y = torch.clamp_min(x,0)
y.backward()
print(x.grad)

tensor(1.)


In [48]:
x = torch.tensor(0.0,requires_grad=True)
y = torch.tensor(2.0,requires_grad=True)
z = torch.tensor(5.0,requires_grad=True)
w = torch.log(torch.exp(x) + torch.exp(y) + torch.exp(z))
w.backward()

print(x.grad)
print(y.grad)
print(z.grad)

tensor(0.0064)
tensor(0.0471)
tensor(0.9465)


In [49]:
x = torch.tensor([[1.0, 2.0]], requires_grad=True)
y = torch.tensor([[3.0, 4.0]], requires_grad=True)
A = torch.tensor([[1.0, 1.0],
                  [1.0, 2.0]])
b = torch.tensor([[1.0, 0.0]])

f = x@A@y.t() + x@b.t()
f.backward()
print(x.grad)
print(y.grad)

tensor([[ 8., 11.]])
tensor([[3., 5.]])


In [50]:
print(x.shape)
z = torch.tensor([1.0,2.0], requires_grad=True)
print(z.shape)

torch.Size([1, 2])
torch.Size([2])
