In [7]:
import numpy as np

dim = 4

In [8]:
np.random.randn(dim+1, 1)

array([[-1.41629135],
       [ 0.80100176],
       [-0.12738849],
       [-1.23024122],
       [-1.28980331]])

In [9]:
np.random.normal(1, 0.1, [dim+1, 1])

array([[0.94701963],
       [0.91547246],
       [0.99101197],
       [0.86932598],
       [0.9913838 ]])

In [10]:
X = np.array([[1,2,3],[4,5,6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.hstack([X, np.ones((X.shape[0], 1))])

array([[1., 2., 3., 1.],
       [4., 5., 6., 1.]])